repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      # Run the linter
      - id: ruff-check
        #args: [--fix]
        files: ^backend/
        types_or: [python, pyi] # Don't run on jupyter notebooks
      # Run the formatter
      - id: ruff-format
        files: ^backend/
        types_or: [python, pyi] # Don't run on jupyter notebooks
